### ISSUE TITLE
'f' issues

### ISSUE THREAD

**Issue by d4ruth** [indestructible-type/Bodoni#1]
'f' doesn't play nice in cursive. Regular 'f' is better but still collides with 'l'.
![example](https://user-images.githubusercontent.com/16523693/51772788-2ba0d300-20aa-11e9-84bc-f4d17000e5a7.png)

**Comment by EwonRael** [comment]
The lower case fl is a ligature, so it's supposed to look like that. However the fl is definitely an issue. I will fix this asap.

Thanks!

Owen

**Comment by EwonRael** [comment]
Okay!

Thank you for pointing this out! 

I just released Bodoni* 1.1 which fixes the fl and ffi ligatures in the italics!

Very embarrassed to even have this problem.

**Comment by d4ruth** [comment]
Is the tail of the lowercase f also supposed to collide with the tail of the j and of the semicolon? I don't know much about fonts, so don't want to open a new issue for something that may not actually be an issue.
