### ISSUE TITLE
Move finished font files to releases

### ISSUE THREAD

**Issue by gosh-darn** [indestructible-type/Bodoni#11]
I know it might just go against the font production conventions here on GitHub, but I am a firm believer in moving the finished binary files (ttfs and otfs) to the releases section. This keeps the sources and exports nicely separated and won’t clutter up the repository as much.

By the way, love the work you are doing here, Owen; keep at it!

**Comment by EwonRael** [comment]
thanks. I'm going to try and keep up with this but no promises okay!

**Comment by davelab6** [comment]
@EwonRael I recommend using the Github Release system, but I think it is also very convenient to have the binaries in the repo. 

Please update the repo layout to follow the structure described here: https://github.com/googlefonts/gf-docs/tree/master/QuickStartGlyphs

**Comment by EwonRael** [comment]
Hmm I am reading up on this. I will restructure repo when I get the chance. I've tried to push things to releases when able. I'll try to be more incremental with updates going forward.
