### ISSUE TITLE
Unicode ſpaces and quads.

### ISSUE THREAD

**Issue by Alice196498** [indestructible-type/Bodoni#12]
The Unicode ſpaces and quadrats are neceſſary for accurate manual juſtification, as well as fine book-work ; furthermore, they are important to have for reproducing works that follow the ſtyle of fine books, or any lines that require manual juſtification in a work.
 Starting with the largeſt, the em quad (U+2003 U+2001) is the ſame ſize as the UPM ſize of the fount, which is 1,000. The en quad (U+2002 U+2000) is half that, or 500. The thick ſpace (U+2004) is ⅓ of the em, the middling ſpace (U+2005) is ¼ the em, the thin ſpace (U+2009 U+202F) is ⅕ the em, the ſix-per-em ſpace (U+2006) is ⅙ the em, and the hair ſpace can be anywhere between ⅛ and ⅟₁₆ of the em quad—I perſonally prefer to ſet it to ⅒, as I find that to be a nice ſize for it. The figure ſpace (U+2007) is the ſame ſize as the tabular numerals, the puctuation ſpace (U+2008) is the width of the period, and the zero-width ſpace (U+200B) is 0. The medium mathematical ſpace is ⁴⁄₁₈ of the em.

**Comment by davelab6** [comment]
@EwonRael were you able to add these? It seems like this should be easy to do, but I am not sure if they will need "eye balling" to make the widths appropriate to the design, or follow the rote math that @Alice196498 describes.

**Comment by EwonRael** [comment]
Hmmmm. Current version doesn't have this. Might be a simple thing to include, but I'm also tempted to inquire about this with my book-making friends as I'm not really someone that's ever used this kind of thing. 

If it's an easy fix I'll push it soon. 👍👍

**Comment by EwonRael** [comment]
New version 2.2 includes this. I followed the advice about the relative relationships to a T, so it should check out.

Let me know!
