### ISSUE TITLE
Noticeable tear in bold italic ampersand in higher optical sizes (≥48)

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Bodoni#13]
![winword_2019-02-08_23-39-35](https://user-images.githubusercontent.com/47187428/52514665-fdb7a480-2bfa-11e9-9e9c-aaad4830b628.png)
TTF as rendered in MS Word 2016.

**Comment by EwonRael** [comment]
I have been thinking about this.

I will fix this and I will add some other features when I can. I'm away right now so working on this will have to wait.

**Comment by davelab6** [comment]
@EwonRael is this fixed?

**Comment by EwonRael** [comment]
Yeah this should be fixed in both branches. I haven't pushed the latest version to the foundry website yet and I was holding off on closing issue reports until I did that, but this should be fixed
