### ISSUE TITLE
Romanian glyhps

### ISSUE THREAD

**Issue by liviuvasilescu** [indestructible-type/Bodoni#15]
Please add “ț” and ”Ț“.

<img width="816" alt="screenshot 2019-03-07 at 17 26 48" src="https://user-images.githubusercontent.com/48325536/53967738-6e6cb680-40fe-11e9-94fc-445c8540acba.png">

**Comment by EwonRael** [comment]
will do!

**Comment by davelab6** [comment]
@EwonRael were you able to do this?

**Comment by EwonRael** [comment]
Yes latest version has these glyphs 👍👍
