### ISSUE TITLE
Diacritics on i are off-centre

### ISSUE THREAD

**Issue by jeanm** [indestructible-type/Bodoni#18]
Hi, thanks so much for open sourcing this amazing font.

I have noticed that the diaeresis and the circumflex are off-centre when placed on the letter _i_:
<img width="296" alt="Screenshot 2020-02-10 at 16 52 58" src="https://user-images.githubusercontent.com/107696/74203858-e3594200-4c25-11ea-9e41-8c8a9459cdb8.png">

Specifically, they seem to be a bit to the left. Perhaps they are centred around the stem-and-serif combination, but I feel like the should be aligned with the stem alone. Compare with the dot on the regular _i_, which looks properly centred to me.

**Comment by EwonRael** [comment]
Yeah I can take a look at this

**Comment by EwonRael** [comment]
Hey!

I redid the accent marks in Bodoni* 2.2

This should now be addressed.

Thanks for the support and feedback!
