### ISSUE TITLE
Dashes are too short

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Bodoni#2]
The dashes are too short. The em dash is about the expected length for an en dash, and the en dash is very close to the hyphen.

**Comment by EwonRael** [comment]
I will fix this in Bodoni 1.2

**Comment by EwonRael** [comment]
so just for the record I thought the metadata issues were pressing enough that I wanted to fix them asap.

I originally said I would fix this in 1.2 but I didn't because the metadata issues were pressing enough that I wanted to get a fix out as soon as I could.

**Comment by davelab6** [comment]
@EwonRael was this fixed?

**Comment by EwonRael** [comment]
yes this is fixed
