### ISSUE TITLE
Request: 6pt optical cut

### ISSUE THREAD

**Issue by thiagovscoelho** [indestructible-type/Bodoni#4]
Since apparently I can write just anything here, I might as well ask for this. I know it’s a big one. A smaller cut would not be strictly necessary, just as many features aren’t. But it would be very useful for:

- Captions
- Screen usage (even at normal text sizes – screens are still generally too low-res for Bodoni)
- Small text in general

As a counterpoint, it is the fashion today to use sans-serifs as support for all of these applications when needed. Still, it would probably be more useful than some of the larger sizes. 

You could probably use it on your Bodoni* website after you made it, too, since some of the friends at r/typography thought that the hairlines on the font (as displayed on the site currently) look “vibrating”.

ITC Bodoni has a 6pt cut and so does HTF Didot – I don’t know if these facts support or hinder the case for making one for Bodoni*, but they are true.

**Comment by davelab6** [comment]
https://github.com/indestructible-type/Bodoni/tree/google/UFO%20Files/06 now exists :)
