### ISSUE TITLE
Small caps.

### ISSUE THREAD

**Issue by Alice196498** [indestructible-type/Bodoni#5]
A ſet of ſmall caps is generally recommened in moſt complete founts, and having them would greatly extend the poſſible uſes of this typeface ; thus, I feel it would be beneficial to add them.

**Comment by EwonRael** [comment]
I agree!

This is quite the undertaking, because I don't want to just include a smaller version of the capital forms. It might take me a while to get around to doing, but I will do this!

**Comment by davelab6** [comment]
@EwonRael what is the status of small caps? :)

**Comment by EwonRael** [comment]
just released version 2.2 which has small caps!
