### ISSUE TITLE
Long s and its ligatures miſſing.

### ISSUE THREAD

**Issue by Alice196498** [indestructible-type/Bodoni#6]
The long s (ſ) and its ligatures, viz. ſi ſl ſſ ſſi ſſl ſb ſk ſh ſt are miſſing, and the addition of theſe ſorts would not only further the verſatility of the typeface, but would alſo enable eaſier reproduction of certain 19th century documents. Traditionally, there is no ſj ligature, but conſidering that there is an fj ligature in the typeface, it would be ſimple to add ; thus, it might be good to include it for the ſake of being complete.

**Comment by EwonRael** [comment]
Hey!

I appreciate your crusade to bring back the long s. I will provide a long s in the next release of Bodoni*, and if I'm feeling motivated I will include the appropriate ligatures. 

I will say that nothing is _simple_ when working with Bodoni* because there are over 50 font files to deal with, but I think the historical significance is valuable enough to warrant the time.

**Comment by Alice196498** [comment]
Thank you very much ! I didn’t know I was famous—ſo it’s being called a _cruſade_ now . . . how intereſting. If I ever edit a typeface or fount to include the long s and ligatures, I find it eaſieſt to modify the f and ligatures thereof to create the new ones ; although, it might be better to draw it ſeparately—it really depends on one’s perſonal preference and the amount of work one wants to put into it, I think.
 You’re right that it’s not exactly _ſimple ;_ I know well the toil that comes with adding even a few ſorts to that many founts. I originally wrote _trivial_ there, but on further conſideration, changed it to _ſimple_—perhaps even that was making light of the effort required—my apologies for my misſtatement : I had no intention of giving the impreſſion that it would be leſs than trifling, given the large number of founts. I ſhould like to make it very clear how much I appreciate your work, as well as the immence effort you put forth not only in your deſign, but alſo to pleaſe the people who ſubmit things here. It’s truly admirable, and I have nothing but reſpect for you therefor.

**Comment by EwonRael** [comment]
finally got around to adding this in the newly released version 2.2!
I don't have all the ligatures but there is a ſt. I may add more as things progress.

Sorry this took a little while, wasn't top on the priority list!
