### ISSUE TITLE
Non-lining figures.

### ISSUE THREAD

**Issue by Alice196498** [indestructible-type/Bodoni#8]
Your typeface includes lining figures, but is lacking non-lining (old ſtyle) figures, which are generally uſed in running body text, as well as for page numbers. Lining figures are generally uſed in tables or in things ſet in all caps.

**Comment by EwonRael** [comment]
Yeah I think having old style figures would be very cool.

I will get on this

**Comment by davelab6** [comment]
@EwonRael is this done?

**Comment by EwonRael** [comment]
new release has both old style and tabular figures, as well as old style tabular figures.
